### ISSUE TITLE
Better summary

### ISSUE THREAD

**Issue by bertob** [kra-mo/hyperplane#15]
The current summary "Manage your files like never before!" is longer than 35 characters, the exclamation mark is off-style, and it's not very descriptive. Maybe "Manage your files with tags", or something else mentioning tags?

**Comment by kra-mo** [comment]
Oh sure, that was just a placeholder. I do want to be consistent with calling them categories (or something else, still haven't decided) instead of tags because they do differ from the traditional idea of tagging. I'll think about something
