### ISSUE TITLE
Use gfvs extended attributes to store tags

### ISSUE THREAD

**Issue by PHHENS** [kra-mo/hyperplane#18]
Dear Developer,

Thanks for your work on Hyperplane. 
It seems to use a sub-directories system to implement tags.
It would be nice to use normal directory structure, and gvfs extended attributes to store tags.
This could allow to preserve user's directory system, and avoid to duplicate files ...

Thanks

**Comment by kra-mo** [comment]
This is explicitly not the goal of the application as explained in the README. For your use case, a Nautilus extension would be more fitting.

**Comment by kra-mo** [comment]
Files are also not duplicated by Hyperplane.

**Comment by kra-mo** [comment]
How is that a problem? That's the whole point.

**Comment by kra-mo** [comment]
Besides, if a folder is in a folder that does not represent a tag, it won't be considered as a possible tag anyway.
