### ISSUE TITLE
aarch64 builds

### ISSUE THREAD

**Issue by magdesign** [kra-mo/hyperplane#22]
Just tried to run on my linux mobilephone, but realized its x86_64 😅

since we are still missing a nice browser, any chance to try aarm64?

or how to compile on alpine?

thanks for your work!

**Comment by kra-mo** [comment]
You can build it like any other Flatpak app in GNOME Builder, just change the target architecture. ARM builds will be provided whenever the app is released.

**Comment by magdesign** [comment]
Thanks.
Hopefully someone out here will do this for us, i am aarch64 mobile only...😅

**Comment by kra-mo** [comment]
*sigh*

Sure, I'll provide [aarch64 builds](https://github.com/kra-mo/hyperplane/actions/runs/7887850435). It only costs Microsoft money anyways.
