### ISSUE TITLE
attempting to tag a file destroys the file

### ISSUE THREAD

**Issue by salarua** [kra-mo/hyperplane#23]
when using the sidebar to tag a file, the file is deleted.

version: v0.4.1-beta, installed from releases
operating system: Fedora Linux 39

steps to replicate:
1. navigate to a tag
2. drag a file to the sidebar and drop it on another tag

**Comment by kra-mo** [comment]
This should not happen. Hovering over a category in the sidebar while dragging and dropping would open that category.

Can you reproduce this? If so, can you send me a video of it?

**Comment by salarua** [comment]
can reproduce. the file completely disappears and cannot be found in any location it could have logically ended up. searching for it doesn't return any results either.

[Screencast from 2024-02-13 17-19-35.webm](https://github.com/kra-mo/hyperplane/assets/104225819/8bde0d45-77b8-418a-832f-25ba7d1ce1d8)

**Comment by kra-mo** [comment]
I think I know what the culprit is. I'll push a fix soon.
