### ISSUE TITLE
Single Click Activate causes items to not deselect

### ISSUE THREAD

**Issue by MonsterObserver** [kra-mo/hyperplane#28]
[Screencast from 2024-03-25 20-42-21.webm](https://github.com/kra-mo/hyperplane/assets/114881134/aaf841af-ca51-44a4-b959-3feeff248ad1)

**Comment by kra-mo** [comment]
So Nautilus just does custom code for this

https://github.com/GNOME/nautilus/blob/e364ba47054b09e45fe88131683308dc53149542/src/nautilus-grid-view.c#L486

There is no way in hell I will do that, sorry, I am closing this as an "upstream" bug
