### ISSUE TITLE
error: Could not find GTK 4 introspection files. Is gobject-introspection installed? on Linux

### ISSUE THREAD

**Issue by ssteinerx** [kra-mo/hyperplane#30]
I set up a virtual environment, installed pygobject and pgi (whatever the heck that is), but `ninja -C build install` stops with the above referenced message.

Any clue what's missing?  The GTK introspection stuff is supposed to already be in pygobject, and it got me past an an error about not being able to import `gi` but this has got me stumped.

Clues?

**Comment by kra-mo** [comment]
> ninja -C build install stops with the above referenced message.

What message?

**Comment by ssteinerx** [comment]
error: Could not find GTK 4 introspection files. Is gobject-introspection installed?

**Comment by kra-mo** [comment]
Well apparently it is not. I don't know anything more than you. You can set `GI_TYPELIB_PATH ` to wherever you installed them if the issue is that it can't find them.

**Comment by kra-mo** [comment]
> The GTK introspection stuff is supposed to already be in pygobject

Also no, it is not. You have to have the introspection files for GTK4 itself installed on your system. The package is usually just called [gobject-introspection](https://packages.fedoraproject.org/pkgs/gobject-introspection/gobject-introspection/).

**Comment by ssteinerx** [comment]
It's there, I'm just not sure why they're not getting hooked up...
```
$ sudo apt install gobject-introspection
[sudo] password for ssteiner: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
gobject-introspection is already the newest version (1.80.1-1).
gobject-introspection set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
```

**Comment by ssteinerx** [comment]
Just for the record, and maybe to add to the install docs, this got me past the gobject-introspection problem. 

```bash
$ sudo apt install python3-gi python3-gi-cairo gir1.2-gtk-4.0
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3-gi is already the newest version (3.48.2-1).
python3-gi-cairo is already the newest version (3.48.2-1).
The following additional packages will be installed:
  gir1.2-graphene-1.0
The following NEW packages will be installed:
  gir1.2-graphene-1.0 gir1.2-gtk-4.0
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 234 kB of archives.
After this operation, 955 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://us.archive.ubuntu.com/ubuntu noble/main amd64 gir1.2-graphene-1.0 amd64 1.10.8-3build2 [11.1 kB]
Get:2 http://us.archive.ubuntu.com/ubuntu noble/main amd64 gir1.2-gtk-4.0 amd64 4.14.2+ds-1ubuntu1 [223 kB]
Fetched 234 kB in 0s (841 kB/s)         
Selecting previously unselected package gir1.2-graphene-1.0:amd64.
(Reading database ... 350192 files and directories currently installed.)
Preparing to unpack .../gir1.2-graphene-1.0_1.10.8-3build2_amd64.deb ...
Unpacking gir1.2-graphene-1.0:amd64 (1.10.8-3build2) ...
Selecting previously unselected package gir1.2-gtk-4.0:amd64.
Preparing to unpack .../gir1.2-gtk-4.0_4.14.2+ds-1ubuntu1_amd64.deb ...
Unpacking gir1.2-gtk-4.0:amd64 (4.14.2+ds-1ubuntu1) ...
Setting up gir1.2-graphene-1.0:amd64 (1.10.8-3build2) ...
Setting up gir1.2-gtk-4.0:amd64 (4.14.2+ds-1ubuntu1) ...
```

**Comment by kra-mo** [comment]
This is not an application-level thing to document, it's generally about building PyGobject apps on Debian.
