### ISSUE TITLE
Implement org.freedesktop.FileManager1

### ISSUE THREAD

**Issue by kra-mo** [kra-mo/hyperplane#9]
Help needed because I'm really not on the top of my DBus game

https://www.freedesktop.org/wiki/Specifications/file-manager-interface/

**Comment by rdbende** [comment]
I might be able to help out. Recently I've worked with DBus stuff.

**Comment by kra-mo** [comment]
Thanks! Do you want to discuss details on Matrix? My username is [kramo:matrix.org](https://matrix.to/#/@kramo:matrix.org).
